import http from 'node:http';
import {accounts} from './accounts.mjs';
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import {fileURLToPath} from 'node:url';
const ROOT=path.dirname(fileURLToPath(import.meta.url));
try{const raw=await fs.readFile(path.join(ROOT,'.env'),'utf8');for(const line of raw.split(/\r?\n/)){const m=line.match(/^([A-Z_]+)\s*=\s*(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].trim().replace(/^['"]|['"]$/g,'')}}catch{}
const PORT=Number(process.env.PORT)||3000,HOST=process.env.HOST||'127.0.0.1',PUBLIC=process.env.PUBLIC_ORIGIN?.replace(/\/$/,'')||'',DATA=path.resolve(process.env.DATA_DIR||path.join(ROOT,'.data'));
if(PUBLIC&&!/^https:\/\/[^/]+$/.test(PUBLIC))throw Error('PUBLIC_ORIGIN must be an HTTPS origin without a path.');
await fs.mkdir(path.join(DATA,'invitations'),{recursive:true});await fs.mkdir(path.join(DATA,'media'),{recursive:true});
let password=process.env.MUBIEY_ADMIN_PASSWORD;let generated=false;if(!password){try{password=await fs.readFile(path.join(DATA,'admin-password'),'utf8')}catch{password=crypto.randomBytes(15).toString('base64url');await fs.writeFile(path.join(DATA,'admin-password'),password,{mode:0o600})}generated=true}
if(password.length<12)throw Error('Use an admin password of at least 12 characters.');
const users=await accounts(DATA,password);
const owns=(u,d)=>!!u&&(d.ownerId||'admin')===u.id;
const idOK=id=>/^[a-f0-9-]{36}$/.test(id);
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data))};
async function body(req,max=16000){let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>max){const e=Error('File or request is too large');e.status=413;throw e}chunks.push(chunk)}return Buffer.concat(chunks)}
const text=(v,max)=>typeof v==='string'?v.trim().slice(0,max):'';
export function validate(d){if(!d||typeof d!=='object')throw Error('Invalid invitation');const clean={name1:text(d.name1,90),name2:text(d.name2,90),heading:text(d.heading,140),message:text(d.message,3000),venue:text(d.venue,180),address:text(d.address,500),date:text(d.date,40),timezone:text(d.timezone,6),theme:['ivory','emerald','rose','midnight','saffron','sage'].includes(d.theme)?d.theme:'ivory',tradition:['General','Muslim','Hindu','Christian','Interfaith','Other'].includes(d.tradition)?d.tradition:'General',mapUrl:text(d.mapUrl,1800),layout:Number.isInteger(d.layout)&&d.layout>=0&&d.layout<18?d.layout:0,schedule:[],photos:[],music:null};
if(clean.date&&(!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}(:\d{2})?[+-]\d{2}:\d{2}$/.test(clean.date)||!Number.isFinite(Date.parse(clean.date))))throw Error('Choose a valid event date and time zone');
if(clean.mapUrl){let u;try{u=new URL(clean.mapUrl)}catch{throw Error('Enter a valid map link')}if(u.protocol!=='https:'||!['google.com','www.google.com','maps.google.com','maps.app.goo.gl','goo.gl','maps.apple.com'].includes(u.hostname))throw Error('Use an HTTPS Google Maps or Apple Maps link')}
if(Array.isArray(d.schedule))clean.schedule=d.schedule.slice(0,8).map(s=>({title:text(s.title,90),time:text(s.time,90),detail:text(s.detail,250)}));return clean}
const docPath=id=>path.join(DATA,'invitations',id+'.json');
async function readDoc(id){if(!idOK(id))return null;try{return JSON.parse(await fs.readFile(docPath(id),'utf8'))}catch{return null}}
async function writeDoc(doc){const temp=docPath(doc.id)+'.'+crypto.randomUUID()+'.tmp';await fs.writeFile(temp,JSON.stringify(doc),{mode:0o600});await fs.rename(temp,docPath(doc.id))}
const attempts=new Map();const queues=new Map();
async function exclusive(id,fn){const prev=queues.get(id)||Promise.resolve();let release;const gate=new Promise(r=>release=r);queues.set(id,gate);await prev;try{return await fn()}finally{release();if(queues.get(id)===gate)queues.delete(id)}}
const QUOTA=(Number(process.env.USER_STORAGE_MB)||250)*1024*1024;
async function usage(owner){let total=0;const docs=await Promise.all((await fs.readdir(path.join(DATA,'invitations'))).filter(f=>f.endsWith('.json')).map(f=>readDoc(f.slice(0,-5))));const ids=new Set(docs.filter(d=>d&&(d.ownerId||'admin')===owner).map(d=>d.id));for(const f of await fs.readdir(path.join(DATA,'media')))if(ids.has(f.slice(0,36)))total+=(await fs.stat(path.join(DATA,'media',f))).size;try{for(const f of await fs.readdir(path.join(DATA,'projects',owner)))total+=(await fs.stat(path.join(DATA,'projects',owner,f))).size}catch{}return total}
const types={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json','.png':'image/png','.jpg':'image/jpeg'};
const server=http.createServer(async(req,res)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Robots-Tag','noindex, nofollow');let origin;try{origin=PUBLIC||`http://${req.headers.host}`;const url=new URL(req.url,origin),p=decodeURIComponent(url.pathname),signed=users.session(req);
if(p.startsWith('/api/')){if(!['GET','HEAD'].includes(req.method)){if(req.headers.origin!==origin)return json(res,403,{error:'Invalid request origin. Check PUBLIC_ORIGIN in your .env.'})}
if(p==='/api/session'&&req.method==='GET')return json(res,200,{authenticated:!!signed,user:users.publicUser(signed),publicOrigin:PUBLIC});
if((p==='/api/login'||p==='/api/register')&&req.method==='POST'){
 const ip=req.socket.remoteAddress,now=Date.now();for(const [k,v]of attempts)if(v.until<now)attempts.delete(k);
 const a=attempts.get(ip)||{count:0,until:now+900000};if(a.count>=20)return json(res,429,{error:'Too many attempts. Wait 15 minutes.'});a.count++;attempts.set(ip,a);
 const d=JSON.parse((await body(req,2000)).toString());const u=p==='/api/register'?await users.register(d.username,d.password):await users.login(d.username,d.password);
 if(!u)return json(res,401,{error:'Incorrect username or password, or account disabled.'});
 res.setHeader('Set-Cookie',`mubiey_session=${users.issue(u)}; HttpOnly; SameSite=Strict; Path=/; Max-Age=43200${PUBLIC?'; Secure':''}`);return json(res,200,{ok:true,user:users.publicUser(u)})}
if(p==='/api/logout'&&req.method==='POST'){users.logout(req);res.setHeader('Set-Cookie','mubiey_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
if(p==='/api/admin/users'&&req.method==='GET'){if(signed?.role!=='admin')return json(res,403,{error:'Admin only'});const docs=await Promise.all((await fs.readdir(path.join(DATA,'invitations'))).filter(f=>f.endsWith('.json')).map(f=>readDoc(f.slice(0,-5))));return json(res,200,{items:await Promise.all(users.all().map(async u=>({...u,invitations:docs.filter(d=>owns(u,d)).length,storageBytes:await usage(u.id)})))})}
if(p.startsWith('/api/admin/users/')&&req.method==='PUT'){if(signed?.role!=='admin')return json(res,403,{error:'Admin only'});return json(res,200,await users.manage(p.split('/').pop(),JSON.parse((await body(req)).toString()).disabled))}
if(p==='/api/projects'||p.startsWith('/api/projects/')){
 if(!signed)return json(res,401,{error:'Sign in to access your files.'});
 const dir=path.join(DATA,'projects',signed.id);await fs.mkdir(dir,{recursive:true});const id=p.split('/')[3];
 if(!id&&req.method==='GET'){const items=await Promise.all((await fs.readdir(dir)).filter(f=>f.endsWith('.json')).map(async f=>JSON.parse(await fs.readFile(path.join(dir,f),'utf8'))));return json(res,200,{items})}
 if(!id&&req.method==='POST')return await exclusive('user:'+signed.id,async()=>{const bytes=await body(req,20*1024*1024);if(await usage(signed.id)+bytes.length>QUOTA)return json(res,413,{error:'Your storage is full. Delete files to free space.'});const type=req.headers['content-type'];if(!['image/png','image/jpeg','application/json','application/pdf'].includes(type))return json(res,400,{error:'Upload PNG, JPEG, PDF or project JSON.'});const id=crypto.randomUUID(),doc={id,name:text(decodeURIComponent(req.headers['x-file-name']||'Project'),120),type,size:bytes.length,updated:new Date().toISOString()};await fs.writeFile(path.join(dir,id),bytes);await fs.writeFile(path.join(dir,id+'.json'),JSON.stringify(doc));return json(res,201,doc)});
 if(idOK(id)){const file=path.join(dir,id);try{const meta=JSON.parse(await fs.readFile(file+'.json','utf8'));if(req.method==='GET'){res.setHeader('Content-Type',meta.type);res.setHeader('Content-Disposition',`attachment; filename="project-${id}.${({'image/png':'png','image/jpeg':'jpg','application/json':'json','application/pdf':'pdf'})[meta.type]}"`);res.setHeader('Cache-Control','no-store');return res.end(await fs.readFile(file))}if(req.method==='DELETE'){await fs.unlink(file);await fs.unlink(file+'.json');return json(res,200,{ok:true})}}catch{return json(res,404,{error:'File not found'})}}
 return json(res,405,{error:'Method not allowed'})}
if(p==='/api/invitations'&&req.method==='GET'){if(!signed)return json(res,401,{error:'Sign in to manage invitations.'});const files=(await fs.readdir(path.join(DATA,'invitations'))).filter(f=>f.endsWith('.json'));const items=await Promise.all(files.map(async f=>{const d=JSON.parse(await fs.readFile(path.join(DATA,'invitations',f),'utf8'));return owns(signed,d)?{id:d.id,name1:d.name1,name2:d.name2,published:d.published,updated:d.updated}:null}));return json(res,200,{items:items.filter(Boolean).sort((a,b)=>b.updated.localeCompare(a.updated))})}
if(p==='/api/invitations'&&req.method==='POST'){if(!signed)return json(res,401,{error:'Sign in before saving.'});return await exclusive('user:'+signed.id,async()=>{const owned=(await Promise.all((await fs.readdir(path.join(DATA,'invitations'))).filter(f=>f.endsWith('.json')).map(f=>readDoc(f.slice(0,-5))))).filter(d=>d&&owns(signed,d));if(owned.length>=200)return json(res,413,{error:'Limit: 200 invitations per account. Delete an old invitation first.'});const d=validate(JSON.parse((await body(req)).toString())),doc={...d,ownerId:signed.id,id:crypto.randomUUID(),published:false,updated:new Date().toISOString()};await writeDoc(doc);return json(res,201,doc)})}
const m=p.match(/^\/api\/invitations\/([a-f0-9-]{36})(?:\/(publish|unpublish|media))?$/);if(m){const [,id,action]=m;if(req.method==='GET'&&!action){const d=await readDoc(id);if(!d||(!owns(signed,d)&&!d.published))return json(res,404,{error:'This invitation is not available.'});return json(res,200,{...d,canEdit:owns(signed,d)})}if(!signed)return json(res,401,{error:'Sign in to edit this invitation.'});return await exclusive('user:'+signed.id,async()=>{const d=await readDoc(id);if(!d||!owns(signed,d))return json(res,404,{error:'Invitation not found'});
if(req.method==='PUT'&&!action){const raw=JSON.parse((await body(req)).toString()),v=validate(raw);v.photos=Array.isArray(raw.photos)?raw.photos.filter(p=>d.photos.includes(p)).slice(0,6):d.photos;v.music=raw.music===null?null:d.music;const doc={...d,...v,updated:new Date().toISOString()};await writeDoc(doc);return json(res,200,doc)}
if(req.method==='POST'&&(action==='publish'||action==='unpublish')){if(action==='publish'&&(!d.name1||!d.name2||!d.date))return json(res,400,{error:'Add both names and the event date before sharing.'});d.published=action==='publish';d.updated=new Date().toISOString();await writeDoc(d);return json(res,200,{id,published:d.published,url:origin+'/invite/'+id})}
if(req.method==='POST'&&action==='media'){const type=req.headers['content-type']?.split(';')[0],photo=['image/jpeg','image/png','image/webp'].includes(type),music=['audio/mpeg','audio/mp4','audio/ogg','audio/wav','audio/x-wav'].includes(type);if(!photo&&!music)return json(res,400,{error:'Use JPG, PNG, WebP, MP3, M4A, OGG or WAV.'});if(photo&&d.photos.length>=6)return json(res,400,{error:'Up to six photos per invitation.'});const bytes=await body(req,(photo?15:25)*1024*1024);if(await usage(signed.id)+bytes.length>QUOTA)return json(res,413,{error:'Your storage is full. Delete projects to free space.'});const mediaId=crypto.randomUUID(),key=id+'-'+mediaId;await fs.writeFile(path.join(DATA,'media',key),bytes);await fs.writeFile(path.join(DATA,'media',key+'.json'),JSON.stringify({type}));const ref='/media/'+id+'/'+mediaId;if(photo)d.photos.push(ref);else d.music=ref;d.updated=new Date().toISOString();await writeDoc(d);return json(res,200,d)}
if(req.method==='DELETE'&&!action){await fs.unlink(docPath(id));const files=await fs.readdir(path.join(DATA,'media'));for(const f of files)if(f.startsWith(id+'-'))await fs.unlink(path.join(DATA,'media',f));return json(res,200,{ok:true})}return json(res,405,{error:'Method not allowed'})})}return json(res,404,{error:'Not found'})}
if(p.startsWith('/media/')){const m=p.match(/^\/media\/([a-f0-9-]{36})\/([a-f0-9-]{36})$/);if(!m){res.writeHead(404);return res.end('Not found')}const d=await readDoc(m[1]);if(!d||(!owns(signed,d)&&!d.published)||(!d.photos.includes(p)&&d.music!==p)){res.writeHead(404);return res.end('Not found')}const key=m[1]+'-'+m[2],meta=JSON.parse(await fs.readFile(path.join(DATA,'media',key+'.json'),'utf8')),file=await fs.readFile(path.join(DATA,'media',key));res.setHeader('Content-Type',meta.type);res.setHeader('Cache-Control','private, no-store');res.setHeader('Accept-Ranges','bytes');const range=req.headers.range?.match(/^bytes=(\d+)-(\d*)$/);if(range){const start=Number(range[1]),end=Math.min(file.length-1,range[2]?Number(range[2]):file.length-1);if(start>=file.length||start>end){res.writeHead(416,{'Content-Range':`bytes */${file.length}`});return res.end()}res.writeHead(206,{'Content-Range':`bytes ${start}-${end}/${file.length}`,'Content-Length':end-start+1});return res.end(file.subarray(start,end+1))}res.setHeader('Content-Length',file.length);return res.end(file)}
if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);return res.end('Method not allowed')}const target=p==='/'?'index.html':p.startsWith('/invite/')?'guest.html':p.replace(/^\//,'');const full=path.resolve(ROOT,'public',target);if(!full.startsWith(path.join(ROOT,'public')+path.sep)){res.writeHead(403);return res.end('Forbidden')}try{const content=await fs.readFile(full);res.setHeader('Content-Type',types[path.extname(full)]||'application/octet-stream');res.setHeader('Cache-Control','no-cache');res.end(req.method==='HEAD'?undefined:content)}catch{res.writeHead(404);res.end('Not found')}
}catch(e){if(!res.headersSent)json(res,e.status||400,{error:e.message||'Could not complete this action.'});else res.end()}});
server.listen(PORT,HOST,()=>{console.log(`\nMUBIEY STUDIO\nOpen: http://${HOST==='0.0.0.0'?'localhost':HOST}:${PORT}\nAdmin username: admin\nInitial admin password: ${generated?password:'(your MUBIEY_ADMIN_PASSWORD)'}\nKeep this terminal open. Ctrl+C stops the server.\n`)});
