import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
import {validate} from '../lib/validate.js';
function renderer(){const c=vm.createContext({location:{origin:'https://studio.example'},Studio:{escape:s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))},URL,console});for(const f of ['live-presets','invitation-renderer','floral-cards','card-renderer','atelier','atelier-experience'])vm.runInContext(fs.readFileSync('public/'+f+'.js','utf8'),c);return c}
test('Atelier saved settings survive validation; 448 editions safely render',()=>{const c=renderer();const data=validate({name1:'<script>alert(1)</script>',name2:'Maya',template:'atelier-3-6-2',font:'italic',animation:false,layout:6});c.data=data;assert.equal(data.template,'atelier-3-6-2');assert.equal(data.font,'italic');const html=vm.runInContext('invitationDocument(data)',c);assert.ok(!html.includes('<script>alert'));assert.ok(!html.includes('id="envelope"'));assert.ok(html.includes('OPEN DIRECTIONS')===false);assert.equal(vm.runInContext('ATELIER_PRESETS.length',c),448);assert.equal(vm.runInContext('new Set(ATELIER_PRESETS.map(p=>atelierCard({name1:"A",name2:"B"},p))).size',c),448)});
test('Atelier guests retain all six photos, motion opening and safe directions',()=>{const c=renderer();c.data={template:'atelier-0-0-0',font:'script',animation:true,photos:Array.from({length:6},(_,i)=>'/media/photo-'+i),mapUrl:'https://maps.google.com/?q=Kuwait'};const html=vm.runInContext('invitationDocument(data)',c);for(let i=0;i<6;i++)assert.ok(html.includes('/media/photo-'+i));assert.ok(html.includes('id="open-invitation"'));assert.ok(html.includes('IntersectionObserver'));assert.ok(html.includes('OPEN DIRECTIONS'));assert.ok(html.includes('prefers-reduced-motion'));c.data._editorPreview=true;assert.ok(!vm.runInContext('invitationDocument(data)',c).includes('id="envelope"'))});
test('Locket and direct opening persist with organic gallery',()=>{const c=renderer();c.data=validate({name1:'A',name2:'B',template:'atelier-4-2-1',openingStyle:'locket',galleryMode:'organic',font:'amiri',animation:true});assert.equal(c.data.openingStyle,'locket');assert.equal(c.data.galleryMode,'organic');assert.equal(c.data.font,'amiri');let html=vm.runInContext('invitationDocument(data)',c);assert.ok(html.includes('locket-half left'));assert.ok(html.includes('locket-half right'));assert.ok(html.includes('startMusic();const cover'));c.data.openingStyle='none';html=vm.runInContext('invitationDocument(data)',c);assert.ok(!html.includes('id="envelope"'))});

test('Music autoplay choice persists and OFF suppresses automatic playback',()=>{const c=renderer();c.data=validate({template:'atelier-4-2-1',openingStyle:'locket',musicAutoplay:false});assert.equal(c.data.musicAutoplay,false);let html=vm.runInContext('invitationDocument(data)',c);assert.ok(!html.includes('startMusic();'));assert.ok(!html.includes("document.addEventListener('pointerdown'"));c.data.musicAutoplay=true;html=vm.runInContext('invitationDocument(data)',c);assert.ok(html.includes('startMusic();'));assert.equal(validate({}).musicAutoplay,true)});

test('Artwork preserves its proportions instead of stretching',()=>{const c=renderer();for(let i=0;i<16;i++){c.art=i;const svg=vm.runInContext('atelierArtwork(art)',c);assert.ok(svg.includes('preserveAspectRatio="xMidYMid slice"'));assert.ok(svg.includes('overflow="hidden"'));assert.ok(!svg.includes('preserveAspectRatio="none"'))}});

test('New collections and preview controls remain editable without entering guest output',()=>{const c=renderer();c.data={template:'atelier-15-0-0',name1:'A',name2:'B',_editorPreview:true};const edit=vm.runInContext('invitationDocument(data)',c);assert.ok(edit.includes('mubiey-direct-text'));assert.ok(edit.includes('mubiey-direct-photo'));c.data._editorPreview=false;const guest=vm.runInContext('invitationDocument(data)',c);assert.ok(!guest.includes('mubiey-direct-text'));assert.ok(!guest.includes('mubiey-direct-photo'));assert.ok(vm.runInContext('atelierCard(data,ATELIER_PRESETS[420])',c).includes('data-edit="name1"'));assert.equal(vm.runInContext('atelierSpec("atelier-99-0-0")',c),null)});
