import {validate} from './validate.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const hex=b=>Array.from(new Uint8Array(b),x=>x.toString(16).padStart(2,'0')).join('');
const random=()=>hex(crypto.getRandomValues(new Uint8Array(32)));
const sha=async s=>hex(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)));
const hash=async(p,s)=>{const k=await crypto.subtle.importKey('raw',new TextEncoder().encode(p),'PBKDF2',false,['deriveBits']);return hex(await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(s),iterations:100000,hash:'SHA-256'},k,256))};
const equal=(a,b)=>{if(a.length!==b.length)return false;let n=0;for(let i=0;i<a.length;i++)n|=a.charCodeAt(i)^b.charCodeAt(i);return n===0};
const cookie=r=>(r.headers.get('cookie')||'').split(';').map(s=>s.trim()).find(s=>s.startsWith('mubiey_session='))?.slice(15)||'';
const publicUser=u=>u?{id:u.id,username:u.username,role:u.role,disabled:!!u.disabled,created:u.created}:null;
const stmt=(e,q,...p)=>e.DB.prepare(q).bind(...p);
async function bytes(r,max){if(Number(r.headers.get('content-length'))>max)fail('File is too large',413);const reader=r.body?.getReader();if(!reader)return new Uint8Array();const chunks=[];let size=0;while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>max){await reader.cancel();fail('File is too large',413)}chunks.push(value)}const out=new Uint8Array(size);let at=0;for(const c of chunks){out.set(c,at);at+=c.length}return out}
const body=async r=>JSON.parse(new TextDecoder().decode(await bytes(r,18000)));
async function user(r,e){const token=cookie(r);if(!token)return null;return stmt(e,'SELECT u.* FROM users u JOIN sessions s ON s.user_id=u.id WHERE s.token=? AND s.expires>? AND u.disabled=0',await sha(token),Date.now()).first();}
async function rate(r,e){const key=await sha((r.headers.get('x-vercel-forwarded-for')?.split(',')[0]||'local')+':'+Math.floor(Date.now()/900000));const a=await stmt(e,'INSERT INTO rates(key,count,expires) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count',key,Date.now()+900000).first();await stmt(e,'DELETE FROM rates WHERE expires<?',Date.now()).run();if(a.count>30)fail('Too many attempts. Please wait 15 minutes.',429)}
const read=async(e,id)=>{const row=await stmt(e,'SELECT * FROM invitations WHERE id=?',id).first();return row?{...row,data:JSON.parse(row.doc)}:null};
async function save(e,row,data){const r=await stmt(e,'UPDATE invitations SET doc=?,updated=?,version=version+1 WHERE id=? AND version=?',JSON.stringify(data),data.updated,row.id,row.version).run();if(!r.meta.changes)fail('This invitation changed in another tab. Reopen it before saving.',409)}
const QUOTA=250*1048576;
async function remove(e,f){await e.BUCKET.delete('files/'+f.id);await e.DB.removeFile(f.id)}
async function prepareUpload(r,e,u){const input=await body(r),type=String(input.type||''),size=Number(input.size),invite=input.invite||null;const photo=['image/png','image/jpeg','image/webp'].includes(type),music=['audio/mpeg','audio/mp4','audio/ogg','audio/wav','audio/x-wav'].includes(type);
if(invite?(!photo&&!music):!['image/png','image/jpeg','application/pdf','application/json'].includes(type))fail('Unsupported file type');const max=invite?(photo?15:25)*1048576:20*1048576;if(!Number.isSafeInteger(size)||size<=0||size>max)fail('File exceeds the upload limit',413);
if(invite){const row=await read(e,invite);if(!row||row.owner!==u.id)fail('Invitation not found',404);if(photo&&row.data.photos.length>=6)fail('Up to six invitation photos')}
const old=await stmt(e,"SELECT * FROM files WHERE owner=? AND status='pending' AND expires<?",u.id,Date.now()).all();for(const f of old.results)await remove(e,f);
const reserve=25*1048576,id=crypto.randomUUID();const held=await stmt(e,'UPDATE users SET used=used+? WHERE id=? AND disabled=0 AND used+?<=? RETURNING id',reserve,u.id,reserve,QUOTA).first();if(!held)fail('Your storage is full. Delete old files or wait for unfinished uploads to expire.',413);
try{await stmt(e,"INSERT INTO files(id,owner,invite,name,type,size,created,status,expected,expires) VALUES(?,?,?,?,?,?,?,'pending',?,?)",id,u.id,invite,String(input.name||'Project').slice(0,120),type,reserve,new Date().toISOString(),size,Date.now()+3*3600000).run()}catch(err){await stmt(e,'UPDATE users SET used=MAX(0,used-?) WHERE id=?',reserve,u.id).run();throw err}
// Retain failed reservations until token expiry: an issued token can still be used.
const uploadUrl=await e.BUCKET.signUpload('files/'+id);return json({id,uploadUrl})}
async function completeUpload(e,u,id){const f=await stmt(e,'SELECT * FROM files WHERE id=? AND owner=?',id,u.id).first();if(!f)fail('Upload not found',404);let row=f.invite?await read(e,f.invite):null;if(f.invite&&(!row||row.owner!==u.id))fail('Invitation not found',404);if(f.status==='ready')return json(row?row.data:{...f,updated:f.created});if(Number(f.expires)<Date.now())fail('Upload expired. Please upload again.');const info=await e.BUCKET.info('files/'+id),size=Number(info.size);if(size!==Number(f.expected)||info.contentType!==f.type)fail('The uploaded file does not match its declared type or size.');let next=null;if(row){const photo=f.type.startsWith('image/'),ref='/media/'+f.invite+'/'+id;next={...row.data,photos:[...row.data.photos],updated:new Date().toISOString()};if(photo){if(next.photos.length>=6)fail('Up to six invitation photos');next.photos.push(ref)}else next.music=ref}await e.DB.finalize(f,row,next,size);return json(next||{id:f.id,name:f.name,type:f.type,size,updated:f.created})}
export default {async fetch(r,e){try{const url=new URL(r.url),p=url.pathname,method=r.method;
if(!p.startsWith('/api/')&&!p.startsWith('/media/'))return json({error:'Not found'},404);
if(!e.DB||!e.BUCKET)return json({error:'Storage is temporarily unavailable. Please try again.'},503);
if(!['GET','HEAD'].includes(method)&&r.headers.get('origin')!==url.origin)fail('Invalid request origin',403);
const u=await user(r,e);
if(p==='/api/session')return json({authenticated:!!u,user:publicUser(u),publicOrigin:url.origin});
if((p==='/api/register'||p==='/api/login')&&method==='POST'){
 await rate(r,e);const d=await body(r),username=String(d.username||'').trim().toLowerCase(),password=d.password;
 if(!/^[a-z0-9_]{3,30}$/.test(username)||typeof password!=='string'||password.length<12||password.length>128)fail('Use a username with 3–30 letters/numbers/underscores and a password with 12–128 characters.');
 let account=await stmt(e,'SELECT * FROM users WHERE username=?',username).first();
 if(p==='/api/login'&&username==='admin'&&!account&&e.ADMIN_PASSWORD?.length>=16){const salt=random();await stmt(e,"INSERT INTO users(id,username,hash,salt,role,created) VALUES(?,?,?,?,'admin',?) ON CONFLICT(username) DO NOTHING",crypto.randomUUID(),'admin',await hash(e.ADMIN_PASSWORD,salt),salt,new Date().toISOString()).run();account=await stmt(e,'SELECT * FROM users WHERE username=?','admin').first();}
 if(p==='/api/register'){if(account||['admin','studio_admin'].includes(username))fail('Username already taken');const salt=random();account={id:crypto.randomUUID(),username,salt,hash:await hash(password,salt),role:'user',created:new Date().toISOString()};try{await stmt(e,'INSERT INTO users(id,username,hash,salt,created) VALUES(?,?,?,?,?)',account.id,username,account.hash,salt,account.created).run()}catch{fail('Username already taken')}}
 else{const candidate=await hash(password,account?.salt||'missing');if(!account||account.disabled||!account.hash||!equal(candidate,account.hash))fail('Incorrect username or password, or account disabled.',401)}
 const token=random();await stmt(e,'DELETE FROM sessions WHERE expires<?',Date.now()).run();await stmt(e,'INSERT INTO sessions(token,user_id,expires) VALUES(?,?,?)',await sha(token),account.id,Date.now()+43200000).run();const response=json({ok:true,user:publicUser(account)});response.headers.set('Set-Cookie',`mubiey_session=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=43200`);return response;
}
if(p==='/api/logout'&&method==='POST'){await stmt(e,'DELETE FROM sessions WHERE token=?',await sha(cookie(r))).run();const response=json({ok:true});response.headers.set('Set-Cookie','mubiey_session=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0');return response}
if(p.startsWith('/api/admin/')){if(u?.role!=='admin')fail('Admin only',403);if(p==='/api/admin/users'&&method==='GET'){const q=await stmt(e,'SELECT u.id,u.username,u.role,u.disabled,u.created,u.used AS "storageBytes",(SELECT COUNT(*) FROM invitations i WHERE i.owner=u.id) AS invitations FROM users u ORDER BY u.created DESC LIMIT 1000').all();return json({items:q.results})}if(method==='PUT'){const d=await body(r);await stmt(e,"UPDATE users SET disabled=? WHERE id=? AND role!='admin'",d.disabled?1:0,p.split('/').pop()).run();return json({ok:true})}fail('Not found',404)}
if(p==='/api/invitations'){if(!u)fail('Sign in to manage invitations',401);if(method==='GET'){const q=await stmt(e,'SELECT id,doc,updated FROM invitations WHERE owner=? ORDER BY updated DESC',u.id).all();return json({items:q.results.map(x=>{const d=JSON.parse(x.doc);return{id:x.id,name1:d.name1,name2:d.name2,published:d.published,updated:x.updated}})})}if(method==='POST'){const d={...validate(await body(r)),id:crypto.randomUUID(),published:false,updated:new Date().toISOString()};const out=await stmt(e,'INSERT INTO invitations(id,owner,doc,updated) SELECT ?,?,?,? WHERE (SELECT COUNT(*) FROM invitations WHERE owner=?)<200',d.id,u.id,JSON.stringify(d),d.updated,u.id).run();if(!out.meta.changes)fail('Limit: 200 invitations per account',413);return json(d,201)}}
const m=p.match(/^\/api\/invitations\/([a-f0-9-]{36})(?:\/(publish|unpublish|media))?$/);
if(m){const [,id,action]=m,row=await read(e,id);if(!row)fail('Invitation not found',404);const mine=u?.id===row.owner,d=row.data;if(method==='GET'&&!action){if(!mine&&!d.published)fail('Invitation not available',404);return json({...d,canEdit:mine})}if(!u)fail('Sign in to edit',401);if(!mine)fail('Invitation not found',404);
 if(method==='PUT'&&!action){const input=await body(r),v=validate(input);v.photos=Array.isArray(input.photos)?input.photos.filter(x=>d.photos.includes(x)).slice(0,6):d.photos;v.music=input.music===null?null:d.music;const next={...d,...v,updated:new Date().toISOString()};await save(e,row,next);return json(next)}
 if(method==='POST'&&(action==='publish'||action==='unpublish')){if(action==='publish'&&(!d.name1||!d.name2||!d.date))fail('Add both names and the event date');d.published=action==='publish';d.updated=new Date().toISOString();await save(e,row,d);return json({id,published:d.published,url:url.origin+'/invite/'+id})}
 if(method==='DELETE'&&!action){const q=await stmt(e,'SELECT * FROM files WHERE invite=? AND owner=?',id,u.id).all();await stmt(e,'DELETE FROM invitations WHERE id=? AND owner=?',id,u.id).run();for(const f of q.results)await remove(e,f);return json({ok:true})}}
if(p==='/api/uploads'&&method==='POST'){if(!u)fail('Sign in to upload',401);return await prepareUpload(r,e,u)}
const upload=p.match(/^\/api\/uploads\/([a-f0-9-]{36})\/complete$/);if(upload&&method==='POST'){if(!u)fail('Sign in to upload',401);return await completeUpload(e,u,upload[1])}
if(p==='/api/projects'||p.startsWith('/api/projects/')){if(!u)fail('Sign in to access your files',401);const id=p.split('/')[3];if(!id&&method==='GET'){const q=await stmt(e,'SELECT id,name,type,size,created AS updated FROM files WHERE owner=? AND invite IS NULL AND status=\'ready\' ORDER BY created DESC',u.id).all();return json({items:q.results})}if(!id&&method==='POST')fail('Use direct storage upload',400);const f=await stmt(e,'SELECT * FROM files WHERE id=? AND owner=? AND invite IS NULL AND status=\'ready\'',id||'',u.id).first();if(!f)fail('File not found',404);if(method==='DELETE'){await remove(e,f);return json({ok:true})}if(method==='GET'){return Response.redirect(await e.BUCKET.signed('files/'+id,'project-'+id+({'image/png':'.png','image/jpeg':'.jpg','application/pdf':'.pdf','application/json':'.json'}[f.type]||'')),302)}}
if(p.startsWith('/media/')){const parts=p.split('/'),id=parts[2],fid=parts[3],row=await read(e,id);if(!row||(!row.data.published&&row.owner!==u?.id)||(!row.data.photos.includes(p)&&row.data.music!==p))fail('Not found',404);return Response.redirect(await e.BUCKET.signed('files/'+fid),302)}
return json({error:'Not found'},404);
}catch(err){console.error('Request failed',err.name);return json({error:err.status?err.message:err instanceof SyntaxError?'Invalid input':'Could not complete this request. Please retry.'},err.status||500)}}};
